import os
import json
from pathlib import Path
from typing import List, Optional, Union
import pandas as pd

# Adjust this path if your processed data lives elsewhere
DEFAULT_DATA_PATH = Path(__file__).resolve().parents[2] / "data" / "processed"

def _parse_embedding(emb: Union[str, List[float], None]) -> List[float]:
    """Normalize the embedding field to a list of floats.

    The source may store the embedding as:
    - a JSON‑encoded string (e.g., "[0.1, 0.2]")
    - an actual Python list (already parsed when reading JSONL)
    - ``None`` or missing – in which case we return an empty list.
    """
    if emb is None:
        return []
    if isinstance(emb, list):
        return emb
    if isinstance(emb, str):
        try:
            return json.loads(emb)
        except json.JSONDecodeError:
            return []
    # Fallback for unexpected types
    return []

def _load_csv(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    if "embedding" in df.columns:
        df["embedding"] = df["embedding"].apply(_parse_embedding)
    return df

def _load_jsonl(jsonl_path: Path) -> pd.DataFrame:
    # Each line is a JSON object representing a pre‑processed log record
    records = []
    with open(jsonl_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                records.append(json.loads(line))
    df = pd.DataFrame.from_records(records)
    if "embedding" in df.columns:
        df["embedding"] = df["embedding"].apply(_parse_embedding)
    return df

def load_preprocessed(limit: Optional[int] = None, data_path: Optional[Path] = None) -> pd.DataFrame:
    """Load the pre‑processed log records generated by Member 1.

    Supports either a CSV named ``preprocessed_logs.csv`` or a JSON‑Lines file
    ``preprocessed_logs.jsonl`` placed in ``data/processed``.

    Returns a :class:`pandas.DataFrame` with columns ``log_id``, ``timestamp``,
    ``source``, ``raw_text``, ``embedding``, ``cpu_percent``, ``memory_percent``.
    """
    if data_path is None:
        data_path = DEFAULT_DATA_PATH
    if not data_path.exists():
        raise FileNotFoundError(f"Processed data directory not found: {data_path}")

    csv_file = data_path / "preprocessed_logs.csv"
    jsonl_file = data_path / "preprocessed_logs.jsonl"
    if csv_file.is_file():
        df = _load_csv(csv_file)
    elif jsonl_file.is_file():
        df = _load_jsonl(jsonl_file)
    else:
        raise FileNotFoundError("Neither preprocessed_logs.csv nor preprocessed_logs.jsonl found in the processed data directory.")

    if limit is not None:
        df = df.head(limit)
    return df
