import json
from pathlib import Path
from typing import List
import numpy as np
import pandas as pd
from ..schemas import DetectionResult
from .data_loader import load_preprocessed
from .baseline import load_isolation_forest, load_kmeans, isolation_forest_score, kmeans_score
from .autoencoder import load_autoencoder, autoencoder_score

# Load thresholds from the config generated by train.py
CONFIG_PATH = Path(__file__).resolve().parents[1] / "models" / "config.json"

def _load_config():
    if not CONFIG_PATH.is_file():
        raise FileNotFoundError(f"Detection config not found at {CONFIG_PATH}. Run train.py first.")
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def _apply_threshold(score: float, threshold: float) -> bool:
    """Return ``True`` if the score indicates an anomaly according to the given threshold."""
    return score >= threshold

def _extract_context(df: pd.DataFrame, idx: int, window: int = 2) -> List[str]:
    """Return a list of raw log texts surrounding the record at *idx*.

    The window size defines how many previous and next records are included.
    """
    start = max(0, idx - window)
    end = min(len(df), idx + window + 1)
    return df.iloc[start:end]["raw_text"].tolist()

def detect(limit: int = None) -> List[DetectionResult]:
    """Run all three detection models on the pre‑processed data and return a list of ``DetectionResult`` objects.

    The function:
    1. Loads the processed DataFrame.
    2. Loads each trained model and its threshold.
    3. Computes a score per model.
    4. Flags an anomaly if **any** model exceeds its threshold.
    5. Packages the result using the shared ``DetectionResult`` schema.
    """
    df = load_preprocessed(limit=limit)
    embeddings = np.stack(df["embedding"].values)

    # Load models and thresholds
    cfg = _load_config()
    thresholds = cfg["thresholds"]
    iso = load_isolation_forest()
    km = load_kmeans()
    ae = load_autoencoder(
        Path(__file__).resolve().parents[1] / "models" / "autoencoder.pkl"
    )

    # Compute scores
    iso_scores = isolation_forest_score(iso, embeddings)
    km_scores = kmeans_score(km, embeddings)
    ae_scores = autoencoder_score(ae, embeddings)

    results: List[DetectionResult] = []
    for i, row in df.iterrows():
        # Combine scores – you could also keep them separate; here we use a simple max.
        combined_score = max(iso_scores[i], km_scores[i], ae_scores[i])
        is_anomaly = (
            _apply_threshold(iso_scores[i], thresholds["isolation_forest"]) or
            _apply_threshold(km_scores[i], thresholds["kmeans"]) or
            _apply_threshold(ae_scores[i], thresholds["autoencoder"])
        )
        result = DetectionResult(
            log_id=row["log_id"],
            anomaly_score=float(combined_score),
            is_anomaly=is_anomaly,
            threshold_used=float(thresholds["autoencoder"]),  # report one of them for reference
            context_window=_extract_context(df, i, window=2),
        )
        results.append(result)
    return results
